# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20170919_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='douban_book',
            name='info',
            field=models.CharField(max_length=200),
        ),
    ]
